### ISSUE TITLE
Add in-person attendance request status

### ISSUE THREAD

**Issue by a2br** [wwdc/2022#30]
That would help spot patterns, and possibly figure out if the process was really random, if it advantaged/disadvantaged students over developers, or if they were treated the same. The ambiguity of the request form might cause some problems here though, as students had a choice between applying as [Their Name] and [A child between 13 and 18 years old], and that might have affected the process.

**Comment by thisIsTheFoxe** [comment]
Thanks for the suggestion.
This project, named "WWDC Students", is focused on people applying for the WWDC Student challenge. And since the Special Event is unrelated to the challenge according to Apple, I don't think it should be included in this repo.
Also, the purpose of this project is to see what other people did, to find inspiration, and share your own work. It's not meant for analysis or data collection.

**Comment by a2br** [comment]
Got it! Thank you for your response.
